"""Contract compiler tests (task 3)."""
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from etch.contracts import compile_contracts
from etch.models import Arrow, Drawing

FIXREPO = Path(__file__).parent / "fixtures" / "fixrepo"
LINT_IMPORTS = shutil.which("lint-imports", path=str(Path(sys.executable).parent))

HEADER = "# Generated by Etch from your architecture drawing. Redraw in Etch instead of editing by hand.\n"


def arrows(*pairs: str) -> list[Arrow]:
    return [Arrow(source=p.split(">")[0], target=p.split(">")[1]) for p in pairs]


def test_exact_output_one_forbidden_contract_per_drawn_source_layer():
    drawing = Drawing(
        layers=["api", "services", "db", "notifications"],
        arrows=arrows("api>services", "services>db", "api>notifications"),
    )
    assert compile_contracts(drawing, "shop") == HEADER + """\
[importlinter]
root_package = shop

[importlinter:contract:etch-api]
name = api may only import: notifications, services
type = forbidden
source_modules =
    shop.api
forbidden_modules =
    shop.db
allow_indirect_imports = True

[importlinter:contract:etch-db]
name = db may only import: nothing
type = forbidden
source_modules =
    shop.db
forbidden_modules =
    shop.api
    shop.notifications
    shop.services
allow_indirect_imports = True

[importlinter:contract:etch-notifications]
name = notifications may only import: nothing
type = forbidden
source_modules =
    shop.notifications
forbidden_modules =
    shop.api
    shop.db
    shop.services
allow_indirect_imports = True

[importlinter:contract:etch-services]
name = services may only import: db
type = forbidden
source_modules =
    shop.services
forbidden_modules =
    shop.api
    shop.notifications
allow_indirect_imports = True
"""


def test_layer_allowed_everything_gets_no_contract_and_undrawn_layers_are_ignored():
    # "notifications" is not drawn: never a source or a forbidden module.
    # Arrows to undrawn layers and self-arrows are ignored.
    drawing = Drawing(
        layers=["api", "db"],
        arrows=arrows("api>db", "api>notifications", "db>db"),
    )
    out = compile_contracts(drawing, "shop")
    assert "[importlinter:contract:etch-api]" not in out
    assert "[importlinter:contract:etch-db]" in out
    assert "notifications" not in out


def test_no_contracts_is_just_the_header_section():
    drawing = Drawing(layers=["api"], arrows=[])
    assert compile_contracts(drawing, "shop") == HEADER + "[importlinter]\nroot_package = shop\n"


@pytest.mark.skipif(LINT_IMPORTS is None, reason="lint-imports not installed in this venv")
def test_lint_imports_breaks_on_violation_and_allows_indirect_chain(tmp_path):
    repo = tmp_path / "repo"
    shutil.copytree(FIXREPO, repo)
    drawing = Drawing(
        layers=["api", "services", "db", "notifications"],
        arrows=arrows("api>services", "services>db"),
    )
    (repo / ".importlinter").write_text(compile_contracts(drawing, "fixpkg"), encoding="utf-8")

    def lint() -> int:
        return subprocess.run(
            [LINT_IMPORTS, "--no-cache"], cwd=repo, capture_output=True
        ).returncode

    assert lint() == 1  # fixpkg.api imports fixpkg.db directly

    # Fix: api only talks to services. api -> services -> db is an indirect
    # chain and must NOT break the contract.
    (repo / "fixpkg" / "api" / "routes.py").write_text(
        "from fixpkg.services.users import get_user\n", encoding="utf-8"
    )
    (repo / "fixpkg" / "api" / "admin.py").write_text(
        "def purge(user_id: int) -> None:\n    pass\n", encoding="utf-8"
    )
    assert lint() == 0
