"""Etch it outputs beyond .importlinter (task 7): PR workflow, Bob skill, Bob mode, the sketch."""
import json

import yaml

from etch.models import Arrow, Drawing, Note
from etch.skillgen import etch_files

DRAWING = Drawing(
    layers=["api", "services", "db", "notifications"],
    arrows=[
        Arrow(source="api", target="services"),
        Arrow(source="services", target="db"),
        Arrow(source="services", target="notifications"),
    ],
)
NOTES = [
    Note(text="all business logic goes through here", source="api", target="services"),
    Note(text="legacy, don't touch"),
]

SKILL = ".bob/skills/etch-architecture/SKILL.md"
MODES = ".bob/custom_modes.yaml"
WORKFLOW = ".github/workflows/etch.yml"
SKETCH = ".etch/drawing.json"


def test_etch_files_paths_in_ui_order():
    assert list(etch_files(DRAWING, "shop", NOTES)) == [WORKFLOW, SKILL, MODES, SKETCH]


def test_workflow_is_valid_yaml_that_runs_the_gate_on_pull_requests():
    text = etch_files(DRAWING, "shop", [])[WORKFLOW]
    doc = yaml.safe_load(text)
    triggers = doc.get(True) or doc.get("on")  # YAML 1.1 reads a bare `on:` key as True
    assert "pull_request" in triggers
    steps = [s.get("run", "") for job in doc["jobs"].values() for s in job["steps"]]
    assert "pip install import-linter==2.15" in steps
    assert "lint-imports --no-cache" in steps


def test_skill_has_bob_frontmatter_rules_and_notes():
    text = etch_files(DRAWING, "shop", NOTES)[SKILL]
    assert text.startswith("---\nname: etch-architecture\ndescription: ")
    front = yaml.safe_load(text.split("---")[1])
    assert front["name"] == "etch-architecture"
    assert "shop" in front["description"]
    for arrow in ("api → services", "services → db", "services → notifications"):
        assert f"- {arrow}" in text
    assert "api, db, notifications, services" in text           # the forbidden set, sorted
    assert "## Architect's notes" in text
    assert "- api → services: all business logic goes through here" in text
    assert "- legacy, don't touch" in text
    assert "lint-imports" in text and ".importlinter" in text


def test_skill_without_notes_has_no_notes_section():
    assert "Architect's notes" not in etch_files(DRAWING, "shop", [])[SKILL]


def test_custom_mode_matches_bobs_schema():
    doc = yaml.safe_load(etch_files(DRAWING, "shop", [])[MODES])
    (mode,) = doc["customModes"]
    assert mode["slug"] == "etch-architect"
    assert mode["name"] == "Etch Architect"
    assert "shop" in mode["roleDefinition"]
    assert "etch-architecture" in mode["customInstructions"]
    assert mode["groups"] == ["read", "edit", "execute", "todo", "skill"]
    assert etch_files(DRAWING, "shop", [])[MODES].startswith("# Generated by Etch")


def test_drawing_json_is_the_sketch_with_notes():
    doc = json.loads(etch_files(DRAWING, "shop", NOTES)[SKETCH])
    assert doc == {
        "version": 1,
        "root_package": "shop",
        "layers": ["api", "services", "db", "notifications"],
        "arrows": [
            {"source": "api", "target": "services"},
            {"source": "services", "target": "db"},
            {"source": "services", "target": "notifications"},
        ],
        "notes": [
            {"text": "all business logic goes through here", "source": "api", "target": "services"},
            {"text": "legacy, don't touch", "source": None, "target": None},
        ],
    }


def test_every_file_ends_with_one_newline():
    for path, text in etch_files(DRAWING, "shop", NOTES).items():
        assert text.endswith("\n") and not text.endswith("\n\n"), path
