/**
 * The hosted demo's stand-in for the backend: the same answers as /api/scan,
 * /api/check and /api/contracts, computed in the browser from a recorded scan.
 * Ports backend/etch/violations.py and backend/etch/contracts.py one-to-one.
 */
import type {
  ArchGraph, CheckRequest, CheckResponse, ContractsResponse, Drawing,
  EtchItRequest, EtchItResponse, PrResponse, ScanRequest, Violation,
} from "../types";
import { DEMO_GRAPH } from "./fixture";

export const STATIC_DEMO = import.meta.env.MODE === "demo";

// The code as it stands: the recorded scan, or the scan after a simulated run
let current: ArchGraph = DEMO_GRAPH;

function wait(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

export function findViolations(graph: ArchGraph, drawing: Drawing): Violation[] {
  const drawn = new Set([...drawing.layers, ...drawing.new_boxes.map((b) => b.id)]);
  const allowed = new Set(drawing.arrows.map((a) => `${a.source}>${a.target}`));
  return graph.dependencies
    .filter((d) => drawn.has(d.source) && drawn.has(d.target) && !allowed.has(`${d.source}>${d.target}`))
    .map((d) => ({ source: d.source, target: d.target, imports: d.imports }))
    .sort((a, b) => (a.source + ">" + a.target).localeCompare(b.source + ">" + b.target));
}

const HEADER =
  "# Generated by Etch from your architecture drawing. Redraw in Etch instead of editing by hand.\n";

export function compileContracts(drawing: Drawing, root: string): string {
  const drawn = [...new Set(drawing.layers)].sort();
  const allowed: Record<string, string[]> = Object.fromEntries(drawn.map((d) => [d, []]));
  for (const { source, target } of drawing.arrows) {
    if (source in allowed && drawn.includes(target) && source !== target && !allowed[source].includes(target)) {
      allowed[source].push(target);
    }
  }
  const lines = [HEADER, "[importlinter]\n", `root_package = ${root}\n`];
  for (const src of drawn) {
    const ok = allowed[src].sort();
    const forbidden = drawn.filter((o) => o !== src && !ok.includes(o));
    if (forbidden.length === 0) continue;
    lines.push(
      "\n",
      `[importlinter:contract:etch-${src}]\n`,
      `name = ${src} may only import: ${ok.length ? ok.join(", ") : "nothing"}\n`,
      "type = forbidden\n",
      "source_modules =\n",
      `    ${root}.${src}\n`,
      "forbidden_modules =\n",
      ...forbidden.map((f) => `    ${root}.${f}\n`),
      "allow_indirect_imports = True\n",
    );
  }
  return lines.join("");
}

/** After a simulated run the code obeys the drawing: broken imports gone, new boxes built. */
export function demoRunFinished(drawing: Drawing): void {
  const broken = new Set(findViolations(current, drawing).map((v) => `${v.source}>${v.target}`));
  const layers = [...current.layers];
  for (const box of drawing.new_boxes) {
    if (!layers.some((l) => l.id === box.id)) {
      layers.push({ id: box.id, module: `${current.root_package}.${box.id}`, files: 1 });
    }
  }
  current = {
    ...current,
    layers,
    dependencies: current.dependencies.filter((d) => !broken.has(`${d.source}>${d.target}`)),
  };
}

export async function scan(_req: ScanRequest): Promise<ArchGraph> {
  await wait(400);
  return current;
}

export async function check(req: CheckRequest): Promise<CheckResponse> {
  return { violations: findViolations(current, req.drawing) };
}

export async function contracts(req: CheckRequest): Promise<ContractsResponse> {
  return { importlinter: compileContracts(req.drawing, current.root_package) };
}

export async function etchIt(req: EtchItRequest): Promise<EtchItResponse> {
  return { written: [".importlinter"], importlinter: compileContracts(req.drawing, current.root_package) };
}

export async function openPr(_req: ScanRequest): Promise<PrResponse> {
  throw new Error("The hosted demo has no repo to push. Run Etch locally to open a pull request.");
}

export async function undo(_repoPath: string): Promise<{ undone: boolean }> {
  current = DEMO_GRAPH;
  return { undone: true };
}
