import { describe, expect, it } from "vitest";
import type { Drawing } from "../types";
import { DEMO_GRAPH } from "./fixture";
import { check, compileContracts, demoRunFinished, findViolations, scan, undo } from "./staticApi";

// The drawing the demo is about: api -> services -> {db, notifications}
const intended: Drawing = {
  layers: ["api", "db", "notifications", "services"],
  arrows: [
    { source: "api", target: "services" },
    { source: "services", target: "db" },
    { source: "services", target: "notifications" },
  ],
  new_boxes: [],
};

describe("hosted demo API", () => {
  it("finds the four planted violations, sorted like the backend", () => {
    const v = findViolations(DEMO_GRAPH, intended);
    expect(v.map((x) => `${x.source}>${x.target}`)).toEqual([
      "api>db", "api>notifications", "db>services", "notifications>db",
    ]);
    expect(v[0].imports[0]).toMatchObject({ file: "shop/api/orders.py", line: 3 });
  });

  it("ignores imports that touch an undrawn box", () => {
    const drawing = { ...intended, layers: ["api", "services"] };
    expect(findViolations(DEMO_GRAPH, drawing)).toEqual([]);
  });

  it("compiles the same .importlinter text as backend/etch/contracts.py", () => {
    // expected text produced by compile_contracts(intended, "shop") in the backend
    const expected =
      "# Generated by Etch from your architecture drawing. Redraw in Etch instead of editing by hand.\n[importlinter]\nroot_package = shop\n\n[importlinter:contract:etch-api]\nname = api may only import: services\ntype = forbidden\nsource_modules =\n    shop.api\nforbidden_modules =\n    shop.db\n    shop.notifications\nallow_indirect_imports = True\n\n[importlinter:contract:etch-db]\nname = db may only import: nothing\ntype = forbidden\nsource_modules =\n    shop.db\nforbidden_modules =\n    shop.api\n    shop.notifications\n    shop.services\nallow_indirect_imports = True\n\n[importlinter:contract:etch-notifications]\nname = notifications may only import: nothing\ntype = forbidden\nsource_modules =\n    shop.notifications\nforbidden_modules =\n    shop.api\n    shop.db\n    shop.services\nallow_indirect_imports = True\n\n[importlinter:contract:etch-services]\nname = services may only import: db, notifications\ntype = forbidden\nsource_modules =\n    shop.services\nforbidden_modules =\n    shop.api\nallow_indirect_imports = True\n";
    expect(compileContracts(intended, "shop")).toBe(expected);
  });

  it("obeys the drawing after a simulated run, and Undo restores the scan", async () => {
    const drawing: Drawing = {
      ...intended,
      arrows: [...intended.arrows, { source: "services", target: "pricing" }, { source: "db", target: "pricing" }],
      new_boxes: [{ id: "pricing", intent: "discount math, no I/O" }],
    };
    demoRunFinished(drawing);
    expect((await check({ drawing })).violations).toEqual([]);
    expect((await scan({})).layers.map((l) => l.id)).toContain("pricing");

    await undo("demo-app");
    expect((await check({ drawing })).violations).toHaveLength(4);
  });
});
