"""Contracts compiler — task 3.

Compiles a Drawing into import-linter contract configuration.
"""
from __future__ import annotations

from etch.models import Drawing

HEADER = (
    "# Generated by Etch from your architecture drawing."
    " Redraw in Etch instead of editing by hand.\n"
)


def compile_contracts(drawing: Drawing, root_package: str) -> str:
    """Return the text of a .importlinter file derived from *drawing*.

    A drawn arrow A→B means "A may import B". Every drawn box gets one
    ``forbidden`` contract listing the drawn boxes it has no arrow to.
    Layers with an arrow covering all other layers produce no contract.
    """
    drawn = sorted(set(drawing.layers))

    # Build allowed[src] = sorted list of targets (both in drawn, src != target)
    allowed: dict[str, list[str]] = {src: [] for src in drawn}
    for arrow in drawing.arrows:
        src, tgt = arrow.source, arrow.target
        if src in allowed and tgt in drawn and src != tgt:
            if tgt not in allowed[src]:
                allowed[src].append(tgt)
    for src in drawn:
        allowed[src] = sorted(allowed[src])

    lines: list[str] = [HEADER, "[importlinter]\n", f"root_package = {root_package}\n"]

    for src in drawn:
        forbidden = sorted(other for other in drawn if other != src and other not in allowed[src])
        if not forbidden:
            continue

        allowed_label = ", ".join(allowed[src]) if allowed[src] else "nothing"
        lines.append("\n")
        lines.append(f"[importlinter:contract:etch-{src}]\n")
        lines.append(f"name = {src} may only import: {allowed_label}\n")
        lines.append("type = forbidden\n")
        lines.append("source_modules =\n")
        lines.append(f"    {root_package}.{src}\n")
        lines.append("forbidden_modules =\n")
        for f in forbidden:
            lines.append(f"    {root_package}.{f}\n")
        lines.append("allow_indirect_imports = True\n")

    return "".join(lines)
