"""FastAPI application for Etch."""
from __future__ import annotations

import ast
import json
import subprocess
import sys
from pathlib import Path

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse, StreamingResponse

from etch.bob_runner import build_prompt, run_bob, stop_current
from etch.contracts import compile_contracts
from etch.gitops import (
    GitError,
    compare_url,
    current_branch,
    discard_changes,
    origin_url,
    push_branch,
    snapshot_branch,
)
from etch.models import (
    ArchGraph,
    CheckRequest,
    CheckResponse,
    ContractsResponse,
    EtchItRequest,
    EtchItResponse,
    MakeItSoRequest,
    PrRequest,
    PrResponse,
    ScanRequest,
)
from etch.scanner import ScanError, detect_root_package, scan_repo
from etch.skillgen import etch_files
from etch.violations import find_violations

app = FastAPI(title="Etch", version="0.1.0")

REPO_ROOT = Path(__file__).resolve().parents[2]


def resolve_repo(repo_path: str) -> Path:
    """Resolve *repo_path* to an absolute directory path.

    An absolute path is used as-is; a relative path is resolved against
    REPO_ROOT. Raises HTTP 400 if the result is not an existing directory.
    """
    p = Path(repo_path)
    if not p.is_absolute():
        p = REPO_ROOT / p
    if not p.is_dir():
        raise HTTPException(status_code=400, detail=f"Not a directory: {repo_path}")
    return p


def root_of(req: ScanRequest, repo: Path) -> str:
    """Return req.root_package, or auto-detect it from the repo directory."""
    return req.root_package or detect_root_package(repo)


@app.exception_handler(NotImplementedError)
def not_implemented_handler(request: Request, exc: NotImplementedError) -> JSONResponse:
    return JSONResponse(status_code=501, content={"detail": str(exc)})


@app.exception_handler(ScanError)
def scan_error_handler(request: Request, exc: ScanError) -> JSONResponse:
    return JSONResponse(status_code=400, content={"detail": str(exc)})


@app.exception_handler(GitError)
def git_error_handler(request: Request, exc: GitError) -> JSONResponse:
    return JSONResponse(status_code=400, content={"detail": str(exc)})


@app.get("/api/health")
def health():
    return {"status": "ok", "version": "0.1.0"}


@app.post("/api/scan")
def scan(req: ScanRequest) -> ArchGraph:
    repo = resolve_repo(req.repo_path)
    return scan_repo(repo, root_of(req, repo))


@app.post("/api/check")
def check(req: CheckRequest) -> CheckResponse:
    repo = resolve_repo(req.repo_path)
    graph = scan_repo(repo, root_of(req, repo))
    return CheckResponse(violations=find_violations(graph, req.drawing))


@app.post("/api/contracts")
def contracts(req: CheckRequest) -> ContractsResponse:
    repo = resolve_repo(req.repo_path)
    return ContractsResponse(importlinter=compile_contracts(req.drawing, root_of(req, repo)))


@app.post("/api/etch-it")
def etch_it(req: EtchItRequest) -> EtchItResponse:
    repo = resolve_repo(req.repo_path)
    root = root_of(req, repo)
    if req.drawing.new_boxes:
        ids = ", ".join(b.id for b in req.drawing.new_boxes)
        raise HTTPException(400, detail=f"Make it so first: {ids} not built yet")
    text = compile_contracts(req.drawing, root)
    (repo / ".importlinter").write_text(text, encoding="utf-8", newline="\n")
    written = [".importlinter"]

    for rel_path, content in etch_files(req.drawing, root, req.notes).items():
        # Never overwrite a user's own .bob/custom_modes.yaml
        target = repo / rel_path
        if rel_path == ".bob/custom_modes.yaml" and target.exists():
            existing = target.read_text(encoding="utf-8")
            if not existing.startswith("# Generated by Etch"):
                continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8", newline="\n")
        written.append(rel_path)

    return EtchItResponse(written=written, importlinter=text)


@app.post("/api/pr")
def open_pr(req: PrRequest) -> PrResponse:
    repo = resolve_repo(req.repo_path)
    base = current_branch(repo)
    sha = snapshot_branch(repo, "etch/make-it-so", req.message)
    pushed = push_branch(repo, "etch/make-it-so")
    url = compare_url(origin_url(repo) or "", "etch/make-it-so", base) if pushed else None
    return PrResponse(branch="etch/make-it-so", commit=sha, pushed=pushed, url=url)


def _built(graph, box_id: str, repo: Path, root: str) -> bool:
    """Return True when *box_id* is a real package with code in it.

    Either a module besides ``__init__.py``, or code (a def, class or assignment)
    in the ``__init__.py`` itself: Bob may put a small package's code right there.
    """
    layer = next((l for l in graph.layers if l.id == box_id), None)
    if layer is None:
        return False
    if layer.files >= 2:
        return True
    init = repo.joinpath(*root.split("."), box_id, "__init__.py")
    try:
        tree = ast.parse(init.read_text(encoding="utf-8"))
    except (OSError, SyntaxError, ValueError):
        return False
    code = (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef, ast.Assign, ast.AnnAssign)
    return any(isinstance(node, code) for node in tree.body)


def make_it_so_stream(repo: Path, root: str, drawing, max_cost: float):
    """Synchronous generator that runs Bob and yields SSE data lines.

    Stream protocol (one JSON object per ``data:`` line):
      {"kind": "violations", "violations": [...]}
      {"kind": "layers", "layers": [...]}
      {"kind": "bob", "event": {...}}
      {"kind": "tests", "ok": bool, "summary": "..."}
      {"kind": "done", "coins": ..., "duration_ms": ..., "violations_left": ..., "boxes_missing": [...]}
      {"kind": "error", "message": "..."}
    """
    import re

    def sse(obj: dict) -> str:
        return f"data: {json.dumps(obj)}\n\n"

    # 1. Initial scan
    try:
        graph = scan_repo(repo, root)
    except ScanError as exc:
        yield sse({"kind": "error", "message": str(exc)})
        return

    # Compute pending new boxes (those not yet built)
    pending = [b for b in drawing.new_boxes if not _built(graph, b.id, repo, root)]

    violations = find_violations(graph, drawing)
    if not violations and not pending:
        yield sse({"kind": "error", "message": "nothing to fix: the code already obeys the drawing"})
        return

    # 2. Always emit initial violations
    last_violations_json = json.dumps([v.model_dump() for v in violations])
    yield sse({"kind": "violations", "violations": [v.model_dump() for v in violations]})

    # Track layer ids for change detection
    last_layer_ids = sorted(l.id for l in graph.layers)

    # 3. Run Bob (with only pending new boxes in the prompt)
    prompt = build_prompt(violations, drawing.model_copy(update={"new_boxes": pending}), root)
    result_event = None

    for ev in run_bob(prompt, repo, max_cost):
        if ev.type == "error":
            yield sse({"kind": "error", "message": ev.data.get("message", "unknown error")})
            return

        yield sse({"kind": "bob", "event": ev.model_dump()})

        if ev.type == "result":
            result_event = ev

        # After every tool_result: rescan
        if ev.type == "tool_result":
            try:
                new_graph = scan_repo(repo, root)
                new_layer_ids = sorted(l.id for l in new_graph.layers)
                if new_layer_ids != last_layer_ids:
                    yield sse({"kind": "layers", "layers": [l.model_dump() for l in new_graph.layers]})
                    last_layer_ids = new_layer_ids
                new_violations = find_violations(new_graph, drawing)
                new_json = json.dumps([v.model_dump() for v in new_violations])
                if new_json != last_violations_json:
                    last_violations_json = new_json
                    yield sse({"kind": "violations", "violations": [v.model_dump() for v in new_violations]})
            except ScanError:
                pass  # file may be half-edited; skip

    # 4. No result event seen
    if result_event is None:
        yield sse({"kind": "error", "message": "Bob stopped before finishing"})
        return

    # 5. Final rescan
    try:
        final_graph = scan_repo(repo, root)
        final_layer_ids = sorted(l.id for l in final_graph.layers)
        if final_layer_ids != last_layer_ids:
            yield sse({"kind": "layers", "layers": [l.model_dump() for l in final_graph.layers]})
            last_layer_ids = final_layer_ids
        final_violations = find_violations(final_graph, drawing)
        final_json = json.dumps([v.model_dump() for v in final_violations])
        if final_json != last_violations_json:
            yield sse({"kind": "violations", "violations": [v.model_dump() for v in final_violations]})
        violations_left = sum(len(v.imports) for v in final_violations)
    except ScanError as exc:
        # Never report success on code Etch can no longer scan (e.g. a syntax error Bob left behind)
        yield sse({"kind": "error", "message": f"Etch could not rescan after Bob's changes: {exc}"})
        return

    # 6. Run the repo's tests
    test_result = subprocess.run(
        [sys.executable, "-m", "pytest", "-q"],
        cwd=repo,
        capture_output=True,
        text=True,
        timeout=300,
    )
    stdout_lines = [l for l in test_result.stdout.splitlines() if l.strip()]
    summary_raw = stdout_lines[-1] if stdout_lines else ""
    # Remove trailing timing like " in 0.05s"
    summary = re.sub(r"\s+in\s+[\d.]+s$", "", summary_raw)
    yield sse({"kind": "tests", "ok": test_result.returncode == 0, "summary": summary})

    # 7. Done
    stats = result_event.data.get("stats", {})
    coins = stats.get("session_costs", 0)
    duration_ms = stats.get("duration_ms", 0)
    boxes_missing = [b.id for b in pending if not _built(final_graph, b.id, repo, root)]
    yield sse({"kind": "done", "coins": coins, "duration_ms": duration_ms, "violations_left": violations_left, "boxes_missing": boxes_missing})


@app.post("/api/make-it-so")
def make_it_so(req: MakeItSoRequest) -> StreamingResponse:
    repo = resolve_repo(req.repo_path)
    root = root_of(req, repo)
    return StreamingResponse(
        make_it_so_stream(repo, root, req.drawing, req.max_cost),
        media_type="text/event-stream",
    )


@app.post("/api/stop")
def stop():
    return {"stopped": stop_current()}


@app.post("/api/undo")
def undo(req: ScanRequest):
    try:
        discard_changes(resolve_repo(req.repo_path))
    except GitError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    return {"undone": True}
