"""Skill generator — task 7.

Generates PR workflow, Bob skill, Bob custom mode and drawing snapshot.
"""
from __future__ import annotations

import json
from typing import Sequence

from etch.models import Drawing, Note

_WORKFLOW = """\
# Generated by Etch: blocks pull requests that break the drawing. No AI in this check, no cost.
name: Etch architecture
on:
  pull_request:
  push:
    branches: [main]
jobs:
  etch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - run: pip install import-linter==2.15
      - name: Code must obey the Etch drawing
        run: lint-imports --no-cache
"""

_SKILL_TEMPLATE = """\
---
name: etch-architecture
description: The architecture of `{root}`, drawn in Etch. Use before adding or moving imports between {root}'s top-level packages, and to fix Etch layering violations.
---

# Architecture rules for `{root}`

These rules were drawn as a sketch in Etch and are enforced on every pull request.

Allowed imports between top-level packages (an arrow means "may import"):
{arrows}

Every other import between {forbidden_set} is forbidden, including imports inside functions or via importlib.
{notes_section}
## How to comply
- Route calls through a package the drawing allows. Never add a forbidden import to get something working.
- Check your work with `lint-imports` (it reads `.importlinter`) and run the tests.
- To change a rule, redraw it in Etch and click Etch it. Do not edit `.importlinter` by hand.
"""

_MODES_TEMPLATE = """\
# Generated by Etch. Redraw in Etch instead of editing by hand.
customModes:
  - slug: etch-architect
    name: Etch Architect
    description: Refactors code so it obeys the Etch drawing
    roleDefinition: >-
      You are an architecture-aware refactoring agent for `{root}`. You keep its
      imports inside the rules drawn in Etch.
    whenToUse: >-
      Use when changing how {root}'s packages depend on each other, or when
      lint-imports reports a broken Etch contract.
    customInstructions: >-
      Read the etch-architecture skill first. Never add an import the drawing
      forbids, including inside functions. Run lint-imports and the tests before
      you finish.
    groups:
      - read
      - edit
      - execute
      - todo
      - skill
"""


def etch_files(drawing: Drawing, root_package: str, notes: Sequence[Note]) -> dict[str, str]:
    """Return the four generated files in UI order, each ending with exactly one newline."""
    # --- arrows ---
    arrows_lines = "\n".join(f"- {a.source} \u2192 {a.target}" for a in drawing.arrows)

    # --- forbidden set (sorted unique layers joined) ---
    forbidden_set = ", ".join(sorted(drawing.layers))

    # --- notes section ---
    note_lines: list[str] = []
    for note in notes:
        if note.source and note.target:
            note_lines.append(f"- {note.source} \u2192 {note.target}: {note.text}")
        else:
            note_lines.append(f"- {note.text}")

    if note_lines:
        notes_section = "\n## Architect's notes\n" + "\n".join(note_lines) + "\n"
    else:
        notes_section = ""

    skill_text = _SKILL_TEMPLATE.format(
        root=root_package,
        arrows=arrows_lines,
        forbidden_set=forbidden_set,
        notes_section=notes_section,
    )

    modes_text = _MODES_TEMPLATE.format(root=root_package)

    drawing_data = {
        "version": 1,
        "root_package": root_package,
        "layers": drawing.layers,
        "arrows": [{"source": a.source, "target": a.target} for a in drawing.arrows],
        "notes": [{"text": n.text, "source": n.source, "target": n.target} for n in notes],
    }
    sketch_text = json.dumps(drawing_data, indent=2, ensure_ascii=False) + "\n"

    return {
        ".github/workflows/etch.yml": _WORKFLOW,
        ".bob/skills/etch-architecture/SKILL.md": skill_text,
        ".bob/custom_modes.yaml": modes_text,
        ".etch/drawing.json": sketch_text,
    }
